mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    path("home/", views.HomeView.as_view(), name="home"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register, name="register"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # ex: /polls/5/choice/
    path("<int:question_id>/choice/", views.choice, name="choice"),
    # ex: /polls/5/vote_reset/
    path("<int:question_id>/vote_reset/", views.vote_reset, name="vote_reset"),
    # ex: /polls/new/
    path("new/", views.add_question, name="new"),
    path("choices/", views.all_choices, name="all_choices"),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    image = models.ImageField(upload_to='questions/', default=None, null=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.core.paginator import Paginator

from django.utils import timezone

from django.shortcuts import get_object_or_404, render, redirect

from .models import Question, Choice

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync


def send_to_lobby(msg):
    channel_layer = get_channel_layer()

    async_to_sync(channel_layer.group_send)(
        'chat_lobby',
        {
            "type": "chat.message",
            'message': msg,
        }
    )

def index(request):
    if request.user.is_authenticated:
        return redirect("/polls/home")
    return render(request, "polls/index.html", {})


class HomeView(LoginRequiredMixin, generic.ListView):
    login_url = "/polls"
    paginate_by = 4
    template_name = "polls/home.html"
    context_object_name = "question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")

class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = "/polls"
    model = Question
    template_name = "polls/detail.html"


class ResultsView(LoginRequiredMixin, generic.DetailView):
    login_url = "/polls"
    model = Question
    template_name = "polls/results.html"

@login_required(login_url="/polls")
def choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'GET':
        return render(request, "polls/choice.html", {"question": question})
    elif request.method == 'POST':
        user_submitted_choice = request.POST["choice"]
        if not user_submitted_choice:
            return render(request, "polls/choice.html", {
                "question": question,
                "error_message": "Please enter a valid choice"
            })

        new_choice = Choice(
            question=question,
            choice_text=user_submitted_choice,
        )
        new_choice.save()
        send_to_lobby(f'<i>{request.user.username}</i> added a new choice to the question <a href="{reverse("polls:detail", args=(question.id,))}">"{question.question_text}"</a>')
        return HttpResponseRedirect(reverse("polls:detail", args=(question.id,)))

@login_required(login_url="/polls")
def vote_reset(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    for choice in question.choice_set.all():
        choice.votes = 0
        choice.save()

    send_to_lobby(f'<i>{request.user.username}</i> reset the votes for question <a href="{reverse("polls:detail", args=(question.id,))}">"{question.question_text}"</a>')
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

@login_required(login_url="/polls")
def add_question(request):
    if request.method == 'GET':
        return render(request, "polls/new_question.html", {})
    elif request.method == 'POST':
        user_submitted_question = request.POST["question"]
        if not user_submitted_question:
            return render(request, "polls/new_question.html", {
                "error_message": "Please enter a valid question"
            })
        
        new_question = Question(
            question_text=user_submitted_question,
            pub_date=timezone.now(),
        )
        new_question.save()
        send_to_lobby(f'<i>{request.user.username}</i> just added a new question <a href="{reverse("polls:detail", args=(new_question.id,))}">"{new_question.question_text}"</a>')
    return HttpResponseRedirect(reverse("polls:home",))

@login_required(login_url="/polls")
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        send_to_lobby(f'<i>{request.user.username}</i> just vote on <a href="{reverse("polls:detail", args=(question.id,))}">"{question.question_text}"</a>')
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def login_user(request):
    data = request.POST
    user = authenticate(request, username=data['username'], password=data['password'])

    if user is not None:
        login(request, user)
        send_to_lobby(f'<i>{request.user.username}</i> just logged in!')
        return HttpResponseRedirect(reverse("polls:home"))
    else:
        return render(request, "polls/index.html", {
            "login_message": "Wrong username/password",
        })


@login_required(login_url="/polls")
def logout_user(request):
    username = request.user.username
    logout(request)
    send_to_lobby(f'<i>{username}</i> just logged out!')
    return HttpResponseRedirect(reverse("polls:index"))

def register(request):
    data = request.POST
    u = User.objects.create_user(
        username=data['username'],
        email=data['email'],
        password=data['password'],
        first_name=data['fname'],
        last_name=data['lname'],
    )

    u.save()
    send_to_lobby(f'<i>{data["username"]}</i> just registered for a new account!')

    return render(request, "polls/index.html", {
        "register_message": "Successfully registered, please login using your email/password now",
    })


def all_choices(request):
    choice_list = Choice.objects.all()

    paginator = Paginator(choice_list, 10)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "polls/choice_list.html", {"page_obj": page_obj})

polls/templates/polls/choice.html
{% extends 'base.html' %}
{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    Add a new choice
{% endblock %}

{% block page_body %}
    <form action="{% url 'polls:choice' question.id %}" method="post">
        {% csrf_token %}
        <h1>You are adding a choice for: "{{ question.question_text }}"</h1>
        {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="choice">Enter your choice: </label>
        <input type="text" value="" name="choice">
        <input type="submit" value="Add" id="choice">
    </form>
{% endblock %}

polls/templates/polls/choice_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    All choices
{% endblock %}

{% block page_body %}
    {% include "polls/includes/header.html" %}
    <ul>
    {% for choice in page_obj %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    {% include "polls/includes/paginator.html" %}
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    Question Detail
{% endblock %}

{% block page_body %}
    {% include "polls/includes/header.html" %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if question.image %}
                <img src={{ question.image.url }} /> <br />
            {% endif %}
            {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
            <a href="{% url 'polls:choice' question.id %}"> Add choice </a>
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock %}

polls/templates/polls/home.html
{% extends 'base.html' %}

{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    Polls Index
{% endblock %}

{% block page_body %}
    {% include "polls/includes/header.html" %}
    {% if question_list %}
        <ul>
        {% for question in question_list %}
            <li title="{{ question.question_text }}">
                <a href="{% url 'polls:detail' question.id %}">
                    {{ question.question_text|truncatechars:20 }}
                </a>
            </li>
        {% endfor %}
        </ul>
        <a href="{% url 'polls:new' %}"> Add question </a> <br />
        <a href="{% url 'polls:all_choices' %}"> All choices </a>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    {% include "polls/includes/paginator.html" %}
{% endblock %}

polls/templates/polls/includes/header.html
<header>
    <nav style='display: flex; justify-content: space-between;'>
        <a href="{% url 'polls:home' %}"> Polls App </a>
        {% if user.is_authenticated %}
        <span style="">
            <a href="{% url 'polls:logout' %}"> Logout </a> 
        </span>
        {% endif %}
    </nav>
</header>

polls/templates/polls/includes/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

polls/templates/polls/index.html
{% extends 'base.html' %}

{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    Welcome to the Polls App!
{% endblock %}

{% block page_body %}
    {% include "polls/includes/header.html" %}
    <h1> Login </h1>
    <form action="{% url 'polls:login' %}" method="post">
        {% csrf_token %}
        {% if login_message %}<p style="color: red"><strong>{{ login_message }}</strong></p>{% endif %}
        <label for="username">Username: </label>
        <input type="text" value="" name="username"> <br/><br/>
        <label for="email">Password: </label>
        <input type="password" value="" name="password"> <br/><br/>
        <input type="submit" value="Login" id="login">
    </form>

    <h1> Register </h1>
    <form action="{% url 'polls:register' %}" method="post">
        {% csrf_token %}
        {% if register_message %}<p style="color: red"><strong>{{ register_message }}</strong></p>{% endif %}
        <label for="fname">First name: </label>
        <input type="text" value="" name="fname"> <br/><br/>
        <label for="lname">Last Name: </label>
        <input type="text" value="" name="lname"> <br/><br/>
        <label for="email">Email: </label>
        <input type="email" value="" name="email"> <br/><br/>
        <label for="username">Username: </label>
        <input type="text" value="" name="username"> <br/><br/>
        <label for="password">Password: </label>
        <input type="password" value="" name="password"> <br/><br/>
        <input type="submit" value="Register" id="register">
    </form>
{% endblock %}

polls/templates/polls/new_question.html
{% extends 'base.html' %}
{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    New Question
{% endblock %}

{% block page_body %}
    <form action="{% url 'polls:new' %}" method="post">
        {% csrf_token %}
        <h1>You are adding a new question!</h1>
        {% if error_message %}<p style="color: red"><strong>{{ error_message }}</strong></p>{% endif %}
        <label for="question">Enter your question: </label>
        <input type="text" value="" name="question">
        <input type="submit" value="Add" id="question">
    </form>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% load static %}

{% block page_links %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% endblock %}

{% block page_title %}
    Results for "{{ question.question_text }}"
{% endblock %}

{% block page_body %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <a href="{% url 'polls:vote_reset' question.id %}">Reset vote?</a>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static '/js/jquery-3.7.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <title> {% block page_title %} Generic Title {% endblock %} </title>
    {% block page_links %} {% endblock %}
</head>
<body>
    {% block page_body %} Empty body {% endblock %}
    <div id="toaster"> </div>
</body>
</html>